# MS Summer Academy NPS Data Exploration (2016-2017)

## Questsions Asked:

    * How many promoters, passives, and detractors are there in both years? How do the scores differ by year?
    * What track of students had the best experience at the summer academy? What about the worst experience?
    * Did students feel as though the pacing increased as the program went on?
    * Which location had the best overall experience?
    * Did students at the NY location have a better or worse expeience as the program went on?
  

# General NPS Cleaning Process:

- Step 1: Import, Clean, and Aggregate Weeks 1-7 for 2016 Data
- Step 2: Import and Clean Week 8 for 2016 Data
- Step 2.5: Aggregate Weeks 1-7 with Week 8 to produce Full 2016 Dataset
- Step 3: Import and Clean 2017 Data
- Step 3.5: Aggregate Full 2016 Data with 2017 Data to produce Complete Dataset

### Promoters, Passives, Detractors for 2017: 78, 34, 8


In [39]:
# Pandas is a library for basic data analysis
import pandas as pd

# NumPy is a library for advanced mathematical computation
import numpy as np

# MatPlotLib is a library for basic data visualization
import matplotlib.pyplot as plt

# SeaBorn is a library for advanced data visualization
import seaborn as sns

import glob

## _Stretch Challenge_:

### Functionalize Data Manipulation code!

In [2]:
sns.set(style="white", context="notebook", palette="deep")

COLOR_COLUMNS = ["#66C2FF", "#5CD6D6", "#00CC99", "#85E085", "#FFD966", "#FFB366", "#FFB3B3", "#DAB3FF", "#C2C2D6"]

sns.set_palette(palette=COLOR_COLUMNS, n_colors=4)

---

# Data Cleaning and Aggregation

In [3]:
REL_PATH_DIRECTORY = "../datasets/SA_Feedback_Surveys_FINAL/2016/"
ALL_BUT_8_PATH = "Anon*.csv"

THE_8_PATH = "Week 8 Feedback (2016, incomplete) - results.csv"

### Weeks 1-7 (2016)

- NOTE: Data is _slightly_ different across various weeks and locations. **Approach with caution!**

In [68]:
all_but_8_2016_files = glob.glob(REL_PATH_DIRECTORY + ALL_BUT_8_PATH)

In [69]:
all_but_8_2016_files

['../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 7 Feedback - Taipei.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - Tokyo.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 1 Feedback - Singapore.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 7 Feedback - LA.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 4 Feedback - SF.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 5 Feedback - SV.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 4 Feedback - SG.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - NY.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 5 Feedback - HK.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 1 Feedback - SF.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 2 Feedback - LA.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - Taipei.csv',
 '../datasets/SA_Feedback_Surveys_FINAL/2016/Anon Week 3 F

## GOAL: Place _Week_ and _Location_ data in each 2016 (not Week 8) DF

In [161]:
filename = "Anon Week 1 Feedback - LA.csv"
fileparts = filename.split(" ")

test_file_path = REL_PATH_DIRECTORY + filename
df_test = pd.read_csv(test_file_path)

In [162]:
week_num, location = int(fileparts[2]), fileparts[5].split(".")[0]

In [171]:
df_garbage = pd.DataFrame([1, 2, 5, 3, 4, 1], columns=["trash_nums"])
df_garbage["Week"], df_garbage["Location"] = week_num, location
df_garbage

trash_nums  Week Location
0           1     1       LA
1           2     1       LA
2           5     1       LA
3           3     1       LA
4           4     1       LA
5           1     1       LA

In [95]:
 
# #Could set location and week columns manually to each file by setting a new DF for each filepath and running this function 
# def addLocationAndWeek(filepath, week, location):
#     location_and_week_arr
#     df = pd.read_csv(filepath)
#     df["Week"] = week
#     df["Location"] = place
#     return dataframe






# week = 48 - 53 
# import re
# # re.find()

# list_of_weeks = list()
# for filepath in all_but_8_2016_files:
#     week = (filepath[48:55])
#     list_of_weeks.append(week)
#     print(week)
    
    

In [251]:
def read_all_files():
    data_arr = list()
    for filename in all_but_8_2016_files:
        # When reading each file, we grab the Week & Location data and add it to two new columns
        week, location = _get_week_and_location(filename)
        df = pd.read_csv(filename)
        df["Week"], df["Location"] = week, location
        data_arr.append(df)
    return data_arr

def _get_week_and_location(filename):
    fileparts = filename.split(" ")
    week, location = int(fileparts[2]), fileparts[5].split(".")[0]
    return week, location

data = read_all_files()

### NOTE: The bad dataframe with `Unnamed: 0` is the `Anon Week 1 Feedback - SV.csv` DF

The `Unnamed: 0` column/feature is measuring Timestamp data (Datetime)

### NOTE: The bad dataframe with no `Timestamp` or `Unnamed: 0` is the `Anon Week 5 Feedback - SF.csv` DF

In [277]:
youre_the_one = None

for df in data:
    if "Unnamed: 0" not in df.columns and "Timestamp" not in df.columns:
        youre_the_one = df
        
youre_the_one

What track are you in?  \
0                    Apps   
1                    Apps   
2                    Apps   
3                    Apps   
4                    Apps   
5                    Apps   
6                    Apps   
7                    Apps   
8                    Apps   
9                    Apps   
10                   Apps   
11                   Apps   
12                   Apps   
13                  Games   
14                  Games   
15                  Games   
16                  Games   
17                  Games   
18                  Games   
19                  Intro   
20                  Intro   
21                  Intro   
22                  Intro   
23                  Intro   
24                  Intro   
25                  Intro   
26                  Intro   
27                  Intro   
28                  Intro   
29                  Intro   
30                  Intro   
31                  Intro   
32                  Intro   
33                  Intro   
34                  Intro   
35                  Intro   
36                     VR   
37                     VR   
38                     VR   
39                     VR   
40                  Intro   
41                  Intro   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                   3                                 
1                                                   4                                 
2                                                   4                                 
3                                                   4                                 
4                                                   3                                 
5                                                   5                                 
6                                                   3                                 
7                                                   5                                 
8                                                   1                                 
9                                                   4                                 
10                                                  5                                 
11                                                  4                                 
12                                                  3                                 
13                                                  4                                 
14                                                  5                                 
15                                                  1                                 
16                                                  5                                 
17                                                  4                                 
18                                                  5                                 
19                                                  5                                 
20                                                  4                                 
21                                                  3                                 
22                                                  5                                 
23                                                  5                                 
24                                                  5                                 
25                                                  5                                 
26                                                  5                                 
27                                                  5                                 
28                                                  5                                 
29                                                  5                                 
30                                                  4     

In [252]:
# week_one_through_seven_df = pd.DataFrame(index=index, columns=columns)

# Find a way to grab `week` and `location` data from filenames
# Find all potential unique columns
# Use unique columns to create master DF and put all data into that one (merging, copies)


column_names = dict()

for df in data:
    for column in df.columns:
        if column in column_names:
            column_names[column] += 1
        else:
            column_names[column] = 1
            
column_names

# for df in data:
#     week_one_through_seven_df = pd.concat(df)
    
# week_one_through_seven_df
# # week_one_through_seven_df .concat()

    
# week_one_through_seven_df + df
    
# week_one_through_seven_df

# rating = 'How would you rate your overall satisfaction with the Summer Academy this week?'
# data[data[rating]==4]

# dataframe["Week"] = week
# dataframe["Location"] = place



{'Timestamp': 37,
 'How would you rate your overall satisfaction with the Summer Academy this week?': 39,
 'How well is the schedule paced?': 33,
 'Week': 39,
 'Location': 39,
 'How well are the tutorials paced?': 6,
 'What track are you in?': 24,
 'Unnamed: 0': 1}

## TODO: Aggregate Schedule and Tutorial data into _Pacing_ column (mutual exclusion)

In [270]:
...

Ellipsis

## Checking Each 2016 (not Week 8) DF for Unique Values

In [253]:
def check_unique_values_by_column(col_name):
    unique_values = set()
    for df in data:
        if col_name in df.columns:
            df_vals = df[col_name].unique().tolist()
            unique_values.update(df_vals)
    return unique_values

In [254]:
col_name_list = list(column_names.keys())
col_name_list

['Timestamp',
 'How would you rate your overall satisfaction with the Summer Academy this week?',
 'How well is the schedule paced?',
 'Week',
 'Location',
 'How well are the tutorials paced?',
 'What track are you in?',
 'Unnamed: 0']

### Create Dictionary of Unique Values per Column Name over All Data

In [278]:
uniques_dict = dict()

# For each column name in our list above, we create a dictionary element where...
# KEY: Column Name
# VALUE: All Unique Values for that Column Name across All Data
for index in range(8):
    col_name = col_name_list[index]
    uniques_dict[col_name] = check_unique_values_by_column(col_name)

In [281]:
uniques_dict["Location"]

{'HK', 'LA', 'NY', 'SF', 'SG', 'SV', 'Singapore', 'Taipei', 'Tokyo'}

In [260]:
schedule_pacing_map = {
    '#REF!': 0, 
    1: 1, 
    2: 2, 
    '2': 2, 
    3: 3, 
    '3': 3, 
    '4': 4, 
    4: 4, 
    5: 5, 
    '5': 5
}

for df in data:
    if "How well is the schedule paced?" in df:
        df["How well is the schedule paced?"] = df["How well is the schedule paced?"].map(schedule_pacing_map)
#         df = df[df["How well is the schedule paced?"] > 0]
        df = df.drop(df[df["How well is the schedule paced?"] > 0].index)
#         df = df.drop(df[df.score < 50].index)

In [262]:
for df in data:
    if "How well is the schedule paced?" in df:
        print(df["How well is the schedule paced?"].unique(), "\n\n")

[3 4] 


[4 3 1 2 5] 


[2 3 4] 


[3 4 2 5] 


[3 4 5 2] 


[3 4] 


[2 3 4 1 5] 


[2 3 4] 


[3 4 2] 


[3 2 4] 


[3 1 4] 


[3 4 2 5] 


[3 4 2] 


[1 3 4 2 5] 


[3 4] 


[2 4 3] 


[2 4 5 3] 


[2 3 4] 


[3 4] 


[3 5] 


[3 4 1 2 5] 


[3 4 5] 


[2 3 5 4] 


[4 5 3 2] 


[3] 


[3 4] 


[5 3 4 2] 


[3 4 2] 


[3] 


[5 3 4] 


[3 2 5 4] 


[3 5 4] 


[ 2.  3.  4.  5. nan] 




In [212]:
unique_types = set()

for item in check_unique_values_by_column(col_name_list[0]):
    unique_types.update([type(item)])
    
unique_types

{float, str}

### Example of Merging Mutually Exclusive Columns

In [120]:
df1 = pd.DataFrame([1, 0, 3, 4, np.nan, np.nan, 0, 6, np.nan, np.nan, np.nan], columns=["a"])
df2 = pd.DataFrame([np.nan, np.nan, np.nan, np.nan, 5, 7, np.nan, np.nan, 2, 9, 8], columns=["b"])

Step 1: Replace all **NaNs**

In [124]:
df1["a"] = df1["a"].fillna(0)
df2["b"] = df2["b"].fillna(0)

In [126]:
df_final = df1['a'] + df2['b']

In [283]:
s1, s2 = "New York", "No Location"
s1 + s2

'New YorkNo Location'

In [127]:
df_final

0     1.0
1     0.0
2     3.0
3     4.0
4     5.0
5     7.0
6     0.0
7     6.0
8     2.0
9     9.0
10    8.0
dtype: float64

### Week 8 (2016)

In [8]:
df_week_8 = pd.read_csv(REL_PATH_DIRECTORY + THE_8_PATH)

In [186]:
df_week_8["Week"] = 8
df_week_8.rename(columns={"location": "Location"}, inplace=True)
df_week_8

#  \
0   00b836bda84e6bdbe780af97e249e59f   
1   39dde6dc0e1e375845d756fc7e39fc5f   
2   5e56b9de91670b308cb98dd2848b8739   
3   641081d05785b47a0f17448625da0d49   
4   c29bdd4f5678d78b450f4494e0f53c8c   
5   9030d8a662b39b519b2b685834413d66   
6   1c07190c7caa72bf6b59cea48e1a4a97   
7   27a63d6c24710feb52c0cfdef7e01175   
8   b47b95f84547d8347119de1da5faa46d   
9   828fafa477484f61d2ca5930fe99ad46   
10  7d70f1e30217d867f3c0f961462d8ae8   
11  65bd071ab808290560e7d11c09f56796   
12  d66976d012b4c8a5c708f1a438605488   
13  9db748a8e0d5789cb3a5fcb27fc59083   
14  5ee2a5d8e87fd5790906f7b004963e14   
15  9826290f1bf2fd4c105857e2af933ffe   
16  ea85e7c699751b5993776ef16db0b1d9   
17  58cb61ce774b116d87e3888d4c1babf1   
18  a08ef61cfa87d1ba00c691de4a55f4c2   
19  630fd265cdb8308b60b4b59351690f0a   
20  2f7303a7ac0943b341d02678b085688e   
21  785568c94d73aa0fad4493ee79fa3974   
22  fe02b118aea0ef15ccd06e6f7e6209f4   
23  6e2c750a71613e3fd7d5f425320cc750   
24  522ff7a7546272c3c98eab026e8c098a   
25  80fce9f8822690ad581ff8d554e6f629   
26  e78c696358f9c59b0375884ab9217f70   
27  4885e461415138a403fb0408a8060094   
28  bb261d3e5b4fe2197f54f28c416948e1   
29  391157a49dc832edb535b3c6ee3dd6a0   
..                               ...   
35  fa299e5db39696d38eafd4ae6e71aebb   
36  35d559a3756563f795c0e9e81299695e   
37  2a42f27c8a19a165f37439cfd9fed33d   
38  1e19d356f6f8eac878413ec736e46da8   
39  a8497fc472b7a09ac6e16e658851d652   
40  3208a7393ff3fd3c67fae17c8e48db37   
41  45d7a66a67ee79f5c9ffa6d6abb1b307   
42  964e2d8e91a04b8735e73aafedb54541   
43  e8780f8e3d0026549c276135fd9569ef   
44  864ff3fc8e19d27f3d4c46eb4b304d35   
45  c2bc67325eb91085f3686aabf309d801   
46  fd802ce8e43aa9deade38c108298dbaf   
47  ac671896bf86167dc073c3f52131fe70   
48  143652af47062192767081ff1dd630cc   
49  f4a5aed1cad9367cc58744706de54a1b   
50  3c3495614eada68b5fa8e19377e1cccd   
51  8e2309e3a1ba2a5630ea251b96712a9a   
52  44db66e47441ecd2c88dbe5dd3a38e1e   
53  80f3d539b648cfaf92b45699e7a0545b   
54  60343ca18c43feedab8481e25421484d   
55  5c99e0aac4efe9eecffd83e50ec7c8db   
56  022d99be229f86182ca1c2bc49aa2e09   
57  5a83e1056e30a8596056bec5c050a86d   
58  50f1c0545d9cef1c10be657e1083990d   
59  22ac2ab300a76178ce53104d03408c8a   
60  2d487d890a68bbdb70dd027bc1e501bb   
61  0cdf8eced1b8791ae536797c75751b25   
62  d353c2cdff6bcf3e932579a5647d511a   
63  f5716831fe432cef5da980038f2f8969   
64  951e9361c4da1756ae1c6fb2612cb9dd   

    How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                  10                                       
1                                                  10                                       
2                                                  10                                       
3                                                   9                                       
4                                                   3                                       
5                                                  10                                       
6                                                   8                                       
7                                                   3                                       
8                                                   6                                       
9                                                   9                                       
10                                                 10                                       
11                                                 10                                       
12                                                  8                                       
13                                                  8                                       
14                                                  8                                       
15                                                 10             

### 2017

In [145]:
FILEPATH = "../datasets/SA_Feedback_Surveys_FINAL/2017/Student_Feedback_Surveys_Superview.csv"
df_2017 = pd.read_csv(FILEPATH)

# 9 or 10 are promoters
# 7-8 are passives
# 0-6 are detractors

# df_2017.head()

# Clean Week data to remove redundant "week"

week_mapper = {
    "Week 1": 1,
    "Week 2": 2,
    "Week 3": 3,
    "Week 4": 4,
    "Week 5": 5,
    "Week 6": 6,
    "Week 7": 7,
    "Week 8": 8
}

df_2017["Week"] = df_2017["Week"].map(week_mapper)

In [146]:
df_2017.head()

ID       Location           Track  Week Rating (Num)    Schedule Pacing
0  134  San Francisco  Apps, Explorer     1            3         Just right
1   36    Los Angeles            Apps     1            4  A little too fast
2  117  San Francisco           Games     1            4       Way too slow
3  253            NaN             NaN     2            4  A little too fast
4  350  New York City  Apps, Explorer     1            4         Just right

In [46]:
df_2017 = pd.read_csv(FILEPATH)
df_2017 = df_2017[df_2017["Rating (Num)"] != "#ERROR!"]
df_2017["Rating (Num)"] = df_2017["Rating (Num)"].astype(int)

df_promoters = df_2017.loc[(df_2017['Rating (Num)'] >= 9) & (df_2017['Week'] == 'Week 7')]
df_passives = df_2017.loc[(df_2017['Rating (Num)'] >= 7) & (df_2017['Rating (Num)'] <= 8) & (df_2017['Week'] == 'Week 7')]
df_detractors = df_2017.loc[(df_2017['Rating (Num)'] < 7) & (df_2017['Week'] == 'Week 7')]


# df_promoters
# df_passives
# df_detractors   

# len(df_promoters) #78
# len(df_passives) #34
# len(df_detractors) #8

# num_of_promoters = len(df_promoters)
# num_of_promoters


8

## Two choices for Pro-Pas-Det Data Divisions:

- **Divide** up your promoters, passives, and detractors into _three_ independent DataFrames
- **Convert** your logic for promoter, passive, and detractor identifiation into _arguments_ that you can pass to your global DataFrame at anytime

---

# Data Manipulation

In [12]:
promoter_count = 0
passive_count = 0
detractor_count = 0

index = []
columns = []

promoter_df = pd.DataFrame(index=index, columns=columns)
passive_df = pd.DataFrame(index=index, columns=columns)
detractor_df = pd.DataFrame(index=index, columns=columns)

In [13]:
arg_promoter = (df["Rating (Num)"] >= 9)
promoters = df[arg_promoter]


# week_one = (promoters["Week"] == "Week 1")

# week_one


# len(promoters)
# promoters

NameError: name 'df' is not defined

In [ ]:
df2017.loc[:, ['ID', 'Track', 'Week', 'Rating (Num)']]


all_students = {}

for index, row in df.iterrows():
    
    